#!/bin/bash

set -e

dest="js"
rm -rf "$dest"
for rb in $(find rb/cfme/tests -name '*.rb'); do
  base=${rb#rb/}
  echo "** $base"
  js="$dest/${base%.rb}.js"
  mkdir -p $(dirname "$js")
  ./rb2js "$rb" > "$js"
done
